[package]
name = "flash-mint-provider-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.flash-mint-provider]
path = ".."

[dependencies.elrond-wasm]
version = "0.17"

[dependencies.elrond-wasm-debug]
version = "0.17"
